### ISSUE TITLE
start-limit-hit

### ISSUE THREAD

**Issue by st0nie** [Petingoso/legion-fan-utils-linux#11]
Using systemctl restart may not be a good idea, if you use fn+q multiple times to switch power-profiles in a short period of time, it may cause start-limit-hit, and then the fan profile switch will no longer work no matter how you switch the power profile.

![image](https://github.com/Petingoso/legion-fan-utils-linux/assets/42872734/2b3f6bcb-d29e-41bf-9ab9-e7680a610b25)

**Comment by MrDuartePT** [comment]
Good catch funny enough never happen to me. This service will be merge in LLL
https://github.com/johnfanv2/LenovoLegionLinux/pull/69
and I make only one service.
